# Generated by Django 4.2.2 on 2023-08-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightsuser',
            name='department',
        ),
    ]
