# Generated by Django 4.2.2 on 2023-07-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_rightsuser_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightsuser',
            name='department',
        ),
    ]
