# Generated by Django 4.2.2 on 2023-07-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('accounts', '0006_alter_rightsuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightsuser',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
