# Generated by Django 4.2.2 on 2023-07-27 21:02

from django.db import migrations, models
import django.db.models.deletion
import rights_management.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('accounts', '0009_alter_rightsuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightsuser',
            name='department',
            field=models.ForeignKey(blank=True, default=rights_management.accounts.models.get_depar, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
