# Generated by Django 4.2.2 on 2023-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('software', models.CharField(choices=[('Accounting Software', 'Accounting Software'), ('Human Resources', 'Human Resources'), ('Customer management', 'Customer management'), ('Design software', 'Design software'), ('Production management', 'Production management'), ('Inventory management', 'Inventory management')], max_length=30)),
            ],
        ),
    ]
