# Generated by Django 4.2.2 on 2023-08-03 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access_rights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_rights',
            name='user',
            field=models.ManyToManyField(related_name='access_rights', to=settings.AUTH_USER_MODEL),
        ),
    ]
