# Generated by Django 4.2.2 on 2023-08-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('access_rights', '0002_access_rights_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=30, unique=True)),
                ('with_permission', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.permission')),
            ],
        ),
    ]
