# Generated by Django 4.2.2 on 2023-08-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_department_owner'),
        ('job_profile', '0004_alter_job_profile_in_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('owner', models.IntegerField(default=1)),
                ('in_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('with_job_profile', models.ManyToManyField(to='job_profile.job_profile')),
            ],
        ),
    ]
