# Generated by Django 4.2.2 on 2023-08-06 19:19

import django.core.validators
from django.db import migrations, models
import rights_management.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('work_people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_people',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), rights_management.accounts.models.only_lettars]),
        ),
        migrations.AlterField(
            model_name='work_people',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), rights_management.accounts.models.only_lettars]),
        ),
    ]
