# Generated by Django 4.2.2 on 2023-08-06 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_owner'),
        ('work_people', '0002_alter_work_people_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_people',
            name='in_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
