# Generated by Django 4.2.2 on 2023-08-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0006_alter_job_profile_in_department'),
        ('work_people', '0003_alter_work_people_in_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_people',
            name='with_job_profile',
            field=models.ManyToManyField(blank=True, null=True, to='job_profile.job_profile'),
        ),
    ]
