# Generated by Django 4.2.2 on 2023-07-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_rights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_access', models.ManyToManyField(to='access_rights.access_rights')),
            ],
        ),
    ]
