# Generated by Django 4.2.2 on 2023-08-04 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_owner'),
        ('job_profile', '0003_job_profile_in_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_profile',
            name='in_department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
