# Generated by Django 4.2.2 on 2023-08-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_owner'),
        ('access_rights', '0002_access_rights_user'),
        ('job_profile', '0004_alter_job_profile_in_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_profile',
            name='in_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
        migrations.AlterField(
            model_name='job_profile',
            name='job_access',
            field=models.ManyToManyField(blank=True, null=True, to='access_rights.access_rights'),
        ),
    ]
