# Generated by Django 4.2.2 on 2023-08-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_owner'),
        ('job_profile', '0005_alter_job_profile_in_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_profile',
            name='in_department',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
