# Generated by Django 4.2.2 on 2023-08-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
